name: Feature Request
description: I'd like to see a new feature added to fun-bots.
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        We always appreciate new ideas for fun-bots, but before posting a new feature idea, maybe we already have it planned? Check the [projects page](https://github.com/Joe91/fun-bots/projects) to see what has been already planned, or it may already planned.
  - type: textarea
    id: feature
    attributes:
      label: Requested feature
      description: What would you like to see added?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Explain in what situations this new feature can be used for, what does it improve or change? Give us an example?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I have checked the following...
      description: Before submitting this new feature request, checkout the contributing guidelines and our code of conduct.
      options:
        - label: I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
          required: true